### ISSUE TITLE
Comments sometimes fail to parse

### ISSUE THREAD

**Issue by chris-martin** [Gabriel439/Haskell-Dhall-Library#117]
There are some unexpected places where comments don't work. For example, `{- comment -} "hi"` works:

```haskell
Prelude Dhall> input auto "{- comment -} \"hi\"" :: IO Text
"hi"
```

But when you reorder it to `"hi" {- comment -}`, it doesn't:

```haskell
Prelude Dhall> input auto "\"hi\" {- comment -}" :: IO Text
*** Exception:
Error: Invalid input

(input):1:6: error: expected: ".",
    ":", end of input, operator
"hi" {- comment -}<EOF>
     ^
```

And it seems like comments never work inside of records or lists.

```haskell
Prelude Dhall> input auto "[1,2, {- comment -} 3]" :: IO (Vector Integer)
*** Exception:
Error: Invalid input

(input):1:8: error: expected: label
[1,2, {- comment -} 3]<EOF>
```

**Comment by Gabriel439** [comment]
Yeah, this is definitely a bug and not intended behavior.  I will take a look at this more closely within the next few days to figure out what is going on
