### ISSUE TITLE
Improve escaping string `\` and `"` in dhall configuration file

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Dhall-Library#13]
I am converting 'shell mappings'; mappings from a name to a shell command.

As an example one mapping looks like so (in a bash file)
```
stats () {
    pepper --client=runner manage.status | jq '.return[0] | [.up , .up + .down | length] as $stats | {up, down, stats: "\($stats[0]) up of \($stats[1])"}'
}
```
I have a turtle script that executes: `nix-shell ... --command 'stats'`.

The idea is to replace such indirection with a direct call (in turtle):
```
 nix-shell ... --command "pepper --client=runner manage.status | jq '.return[0] | [.up , .up + .down | length] as \$stats | {up, down, stats: \"\(\$stats[0]) up of \(\$stats[1])\"}'"
```
And get the command string from a configuration file (read by `dhall`).

Unfortunately because of the default `haskell` escaping rules I have to come up with this:
```
{ stats = "pepper --client=runner manage.status | jq '.return[0] | [.up , .up + .down | length] as \\$stats | {up, down, stats: \\\"\\(\\$stats[0]) up of \\(\\$stats[1])\\\"}'"
}
```
A rather insane escaping mess ... I need to replace all `\` with `\\`  and `\"` with `\\\"`.

Is there a way to tell `dhall` to ignore all escape sequences (maybe with another string delimiter)  ?

Any other advices would be welcomed. Thanks for your help.

PS: I believe this is actually a good use case for `dhall` because some of these 'mappings' require a set of arguments, some of them optional (managing those with shell functions is a pain)

**Comment by Gabriel439** [comment]
I think the best solution here is to have Dhall provide support for Nix's "double single quote" string literals (except perhaps without antiquotation for the first draft)

**Comment by Gabriel439** [comment]
Alright, so with `master` you can now write:

```
{ stats = ''
    pepper --client=runner manage.status | jq '.return[0] | [.up , .up + .down | length] as $stats | {up, down, stats: "\($stats[0]) up of \($stats[1])"}'
  ''
}
```

... just like in Nix
