### ISSUE TITLE
Bash backend

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Dhall-Library#15]
Given a `record` file : 
```
{ foo = True
, baz = "hello"
, bar = 2
}
```
I would like to access `bar` using the `dhall` program alone (no haskell) inside a shell file.

I guess there is a simple trick but I don't see it ;-)

**Comment by Gabriel439** [comment]
You can do:

```bash
$ dhall <<< '(./record ).bar'
```

**Comment by PierreR** [comment]
Thanks that is very helpful.

**Comment by PierreR** [comment]
Would it actually make sense to have a shell backend for `Dhall` ?

For instance if I want to store bar within a shell I can do 
```
v=$(dhall <<< '(./record ).bar ' 2> /dev/null )
```
v is `2` as expected but as soon as I have a List or Optional type it gets much tricky.

**Comment by Gabriel439** [comment]
Yeah, that is a great idea!

**Comment by eternaleye** [comment]
There are a few options for this:

1. Dhall can presume bash, and emit `List`s as quoted values separated by the first character in `$IFS`
    - This permits things like `declare -a DHALL_VAL=( $(dhall ./record 2 >/dev/null) )`
    - Maps could be emitted as IFS-separated `["key"]="val"`, for use with `declare -A`
2. Dhall can emit the entire declaration syntax itself, for use with `eval`
    - This permits representing `Optional`s `None` via `unset`, where (1) would suffer the semipredicate problem
3. Emit shell functions
    - Certainly the hairiest, though possibly the most flexible
    - Requires dhall output a function defintion which, internally, may invoke eval on calling dhall to bind sub-elements
    - User must `eval` the root extraction
4. As any of the above, but have some way to specify the shell to generate for

Note, however:
1. AFAIK, no shell supports nesting of either arrays or associative arrays (maps)
2. Some shells support only arrays, and not associative arrays
3. Some shells support neither

A viable option for all of these cases might be to simply _extract_ the relevant sub-portion of the Dhall expression, and use Dhall on the extracted sub-portion to extract sub-components of that later. If Dhall can emit an IFS-sparated stream of quoted keys, and can produce the length of a list, then pretty much any shell's own looping primitives can do the rest of the work.

**Comment by Gabriel439** [comment]
Another advantage of approach 2 is that instead of using an associative array to represent records you can bind fields to environment variables of the same name.  So if your `dhall` file were:

```
{ foo = 1
, bar = "ABC"
}
```

That would correspond to:

```bash
declare foo=1
declare bar="ABC"
```

I don't think we need to worry about nesting lists.  If Bash doesn't have a way to represent it then we don't need to support it

Also, note that we can represent `Optional` using Bash arrays (keeping consistent with Dhall, which uses list notation for `Optional` values).

**Comment by eternaleye** [comment]
Well, modeling `Optional` using arrays has negative impacts on legibility and idiomatic use of Bash.

It'd require testing for `[val]` as `[[ $#field -ne 0 ]]` (cumbersome array length syntax; numeric equality is second-class) which is very unidiomatic, while expressing `None` as unset and `[val]` as set yields the much more idiomatic `[[ -v $field ]]` ("$field has a value") and matches common use of Bash. It also then permits the `${field:-default_value}` syntax, and avoids the need to use `${field[0]}` to extract the value.

**Comment by Gabriel439** [comment]
Ah, good point.  Yeah, in that case we should treat `Optional` fields as unset variables and set fields as normal (non-array) variables

**Comment by eternaleye** [comment]
Another thing is that if option (2) is chosen, then Dhall can handle top-level records

1. With second-level records as associative arrays
2. With second-level arrays as arrays

but will have trouble with

1. Top-level arrays (no name)
2. Top-level values (same)
3. Any further nesting (inexpressible in plain Bash)

Those issues can all be worked around - using a schema can force an error in case (1) or (2) where a record is expected, and a `--name N` parameter can handle non-record top-levels (though the behavior of `--name` on a record type is up for debate - field prefixing?).

Furthermore, if Dhall grows a `--primitive` flag (that returns 0 if the expression is a primitive, and 1 if it's an aggregate), bash can use that with `if` in order to unpack nested values so long as Dhall simply extracts their expression text.

**Comment by Gabriel439** [comment]
Alright, I finally got around to doing this over the weekend.  You can see what I have so far here:

https://github.com/Gabriel439/Haskell-Dhall-Bash-Library

I ended up deciding to provide two modes:

*   By default, the `dhall-to-bash` compiles to a Bash expression and only supports `Text`, `Integer`, `Natural`, and `Bool` (Note: I haven't added support for `Bool` yet):

    ```bash
    $ dhall-to-bash <<< '"ABC"'
    ABC
    $ dhall-to-bash <<< '" X "'
    $' X '
    $ dhall-to-bash <<< '1'
    1
    $ dhall-to-bash <<< '+1'
    1
    $ dhall-to-bash <<< 'True'
    true
    $ dhall-to-bash <<< 'False'
    false
    ```

*   You can optionally supply a `--declare VAR` flag to emit to a `declare` statement defining that variable compatible with `eval`, which allows you to additionally support `Optional`, `List`, and records

    ```bash
    dhall-to-bash --declare FOO <<< '"ABC\n"'
    declare -r FOO=$'ABC\n'
    $ dhall-to-bash --declare FOO <<< '1'
    declare -r -i FOO=1
    $ dhall-to-bash --declare FOO <<< '[1] : Optional Integer'
    declare -r -i FOO=1
    $ dhall-to-bash --declare FOO <<< '[[1] : Optional Integer] : Optional (Optional Integer)'
    declare -r -i FOO=1
    $ dhall-to-bash --declare FOO <<< '[] : Optional Integer'
    unset FOO
    $ dhall-to-bash --declare FOO <<< '[1, 2, 3] : List Integer'
    declare -r -a FOO=(1 2 3)
    $ dhall-to-bash --declare FOO <<< '{ bar = 1, baz = "ABC" }'
    declare -r -A FOO=([bar]=1 [baz]=ABC)
    ```


All `declare` statements add the `-r` (readonly) flag to ensure that the generated values are immutable (to match the semantics of Dhall as closely as possible) and to avoid overwriting existing variables.  If users want to opt out of this they have to follow up by removing the readonly bit with an additional `declare` statement

`Integer` and `Natural` are `declare`d with the `-i` flag to indicate that they are Bash integers

Let me know what you both think

**Comment by PierreR** [comment]
With one `dhall` file that I use I have got:
```
Explanation: Only primitive values can be translated from Dhall to a Bash
expression

The following Dhall expression could not be translated to a Bash expression:

↳ [{ checkout = "vcsh clone git@mygithub.com:PierreR/devbox-dotfiles.git local", path = "$HOME/.config/vcsh/repo.d/local.git" }]
```
Which seems to imply that a list of record cannot be translated ?

**Comment by Gabriel439** [comment]
@PierreR: Yes, that's correct.  That's mainly because it's not clear how you would represent a list of records in Bash

**Comment by Gabriel439** [comment]
Alright, I published the first version of `dhall-bash` to Hackage so I'll mark this complete for now.  If you have any additional requests you can open issues against the `dhall-bash` repository here:

https://github.com/Gabriel439/Haskell-Dhall-Bash-Library

**Comment by PierreR** [comment]
@Gabriel439 Thanks !
