### ISSUE TITLE
Why [] and [] for the type & value?

### ISSUE THREAD

**Issue by Profpatsch** [Gabriel439/Haskell-Dhall-Library#17]
You have a hard restriction that we must specify a type for the list value, because it’s not clear whether it’s the type or the empty list.

This leads to … interesting config files in practice.

Idea:

change the value `[]` to the symbol `empty`.

**Comment by Gabriel439** [comment]
Dhall does not use `[]` for the list type.  The list type is denoted by the word `List`, not by brackets.  Brackets are only used for list values.

It's also not clear to me what problem is solved by changing `[]` to `empty`.  However, you can very easily do that on your own by just creating the following file:

```bash
$ cat ./empty
λ(a : Type) → [] : List a
```

... and then using `./empty` whenever you want a polymorphic empty list.

**Comment by Profpatsch** [comment]
> Dhall does not use [] for the list type.

Ah, I remembered that wrong. Nvm then.

**Comment by Profpatsch** [comment]
I can’t find the reason why you need the mandatory type annotation on lists, was that documented somewhere @Gabriel439?

**Comment by Gabriel439** [comment]
@Profpatsch: The original explanation is here: https://github.com/Gabriel439/Haskell-Dhall-Library/issues/1#issuecomment-264295194

... and a condensed version of that explanation is in a FAQ section at the end of the tutorial: https://github.com/Gabriel439/Haskell-Dhall-Library/blob/master/src/Dhall/Tutorial.hs#L2135

**Comment by Profpatsch** [comment]
> a condensed version of that explanation is in a FAQ section at the end of the tutorial

Ah, was searching on hackage, looks like you haven’t pushed it yet.

**Comment by Gabriel439** [comment]
Yeah, I'm about to push a new version to Hackage right now
