### ISSUE TITLE
Dealing with Dhall.input error message

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Dhall-Library#25]
The default `dhall` error message is a bit hard to digest for user. Here is an example:
```
cicd: 
↳ /vagrant/config/shell 
/vagrant/config/shell:8:1: error: expected: "[",
    "\8704", "\955", "\\", "forall",
    "if", "let", "merge"
{ loginId      = "jdoe" 
^
```
I can easily catch "SomeException" to prefix the message. For instance:
```
→ result/bin/cicd prod facts
Fail to read configuration file
cicd: 
↳ /vagrant/config/shell 
/vagrant/config/shell:8:1: error: expected: "[",
    "\8704", "\955", "\\", "forall",
    "if", "let", "merge"
{ loginId      = "jdoe" 
^        
```
Except that ideally it would be nice to append the prefix after the name of the program. As the use case is probably quite common, it might be a bit unfair to ask the library user to always deal with the exception (for instance by wrapping the call to `input` with a `try`).

I have noticed as well that the error itself is not really helpful in this case because it actually happens in the next line : 

```
{ loginId      = "jdoe"
, password  = 'secret"
}
```

**Comment by Gabriel439** [comment]
Yeah, I can definitely fix the parse error to point to the correct line.  This was a parsing sloppiness that I forgot to fix due to backtracking unnecessarily

However, I would caution against adding an error message like "Fail to read configuration file" for a couple of reasons, because Dhall can read the configuration file just fine.  The actual error is that Dhall could not parse the file.  However, I can add another line making it clear what type of error it was like "Could not parse X file"

**Comment by PierreR** [comment]
I was using the word `read` because some user (which are not programmers) might be scared by the word "parse" ... For them all it matters is to know that they have filled in the configuration file incorrectly and a way to know how to fix that.

**Comment by PierreR** [comment]
But I see your point `parse` is better than `read`. Maybe there is another one less techy ?

**Comment by Gabriel439** [comment]
How about "syntax error"?

**Comment by Gabriel439** [comment]
Another possibility is "malformed/invalid input/code"

**Comment by PierreR** [comment]
I like both 'syntax error' and 'malformed/invalid input'

**Comment by Gabriel439** [comment]
Alright, so baa08c649872a058b75c71b89bc6e43c231e94b0 fixes the parsing error not being helpful.  Now you should get this error message with the same input:

```
$ dhall
{ loginId      = "jdoe"
, password  = 'secret"
}
(stdin):2:15: error: expected: "''",
    "(", "+", "-", "[", "\8704",
    "\955", "\\", "forall", "if",
    "let", "merge", built-in value,
    double, import, integer, label,
    list literal, natural,
    record literal, record type,
    string, union literal,
    union type
, password  = 'secret" 
              ^        
```

**Comment by PierreR** [comment]
@Gabriel439 Would you know by any chance what might go wrong with terminal input (I am using `urxvt`)

If I make this kind of mistake:
```
{ userName       = ""
, mrRepos        = [puppet-bos", "puppet-irisbox"]
}
 
```
I have the caret to point to the exact correct location when I copy paste the error but when I see it
on the terminal or with github preview I have got:

![capture2](https://cloud.githubusercontent.com/assets/93115/23588719/e6897f82-01c1-11e7-9343-bdb46e3a436c.PNG)

![capture3](https://cloud.githubusercontent.com/assets/93115/23588943/435e095a-01c5-11e7-8bbf-510d6fe9a6b5.PNG)


I am using this [two fonts](https://github.com/PierreR/dotfiles/blob/master/.Xresources#L25-L26) and I will get the same result when changing the precedence order.

**Comment by Gabriel439** [comment]
@PierreR: Where does the caret point when you copy past the error?  Also, the two screenshots of your terminal look like the correct error location to me

**Comment by PierreR** [comment]
When I copy paste the error, the caret points to '[' just before the 'p' of 'puppet' which seems like a better place.

**Comment by Gabriel439** [comment]
Actually, the correct place should be underneath the dash.  It's parsing it as a list whose first element is the variable `puppet`.  If the parser is behaving well then the caret should get as far as possible before the parse fails.

The way you can tell that the caret is supposed to be pointing to the dash is that the list of expected tokens are all valid tokens that can follow the variable `puppet` but they are not valid tokens for the immediate beginning of the list

This indicates that the real issue is probably due to the copy-paste not working correctly.

**Comment by PierreR** [comment]
Thanks. That makes sense. Indeed it is the copy/paste that is off.

Still if I change the input for:
```
, mrRepos        = [puppetbos", "puppet-irisbox"]
```
Then it is failing on:
```
/vagrant/config/box:13:40: error: expected: ",",
    ".", ":", "@", "]", operator
, mrRepos        = [puppetbos", "puppet-irisbox"] 
                                       ^   
```
I guess the parser doesn't know that a variable `puppet"` is not valid ?

**Comment by Gabriel439** [comment]
The parser is still correct and is parsing as far as possible before hitting an error

The parser interprets it as a function named `puppetbos` whose first argument is the string `", "` and whose second argument is `puppet` and then fails on the dash, which is not a valid Dhall symbol

**Comment by PierreR** [comment]
The parser doesn't expect a space after the a function name ?

**Comment by Gabriel439** [comment]
Space is not required between a function and a string argument (just like Haskell).  For example, this is legal:

```haskell
λ(f : Text → Bool) → f"foo"
```

**Comment by PierreR** [comment]
That's quite amazing. I have never thought it'd be legal in `Haskell` .
I would argue it should not be in `dhall` just to make error messages easier to understand by mere mortal ;-)

**Comment by PierreR** [comment]
And to encourage readability.

**Comment by Gabriel439** [comment]
Even if spaces were mandatory between functions and their arguments it still wouldn't solve the problem.  You could have had this:

```
, mrRepos        = [puppetbos ", "puppet-irisbox"] 
```

... and the error still would have persisted and then you would have inconsistent parse errors based on whether or not they had space at the end of their string

It would also make the language much more difficult to lex and be a huge deviation from how other languages behave.  Most languages (not just Haskell) use a longest match lexer and completely ignore whitespace, but if you treat whitespace between functions and their arguments differently then things get more complex

**Comment by PierreR** [comment]
Fair enough. Thanks for the detailed explanation. It is easier to cope with this knowing why it occurs.

**Comment by Gabriel439** [comment]
You're welcome!
