### ISSUE TITLE
Add the ability to customize the pgrname error message prefix

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Dhall-Library#32]
Thanks to #25 the error message displays by `dhall` is much better.

But somehow I still believe it would be nice if I could optionally change the 'program name' line with a more custom (business related) one. 

As an example, in my case, whenever an error occurs instead of "
```
cicd:
↳ /vagrant/config/shell
 
Error: Invalid input
```
I would display:
```
Fail to load configuration file: 
↳ /vagrant/config/shell 

Error: Invalid input
```

Cheers,

**Comment by Gabriel439** [comment]
The program name is not inserted by `dhall` (either the library or the executable).  That's inserted by the Haskell runtime system any time an unhandled exception floats up to the top level

So if you want to get rid of the program name, just catch and handle all exceptions.  For example the `dhall` executable has a fallback handler here for exactly this reason: https://github.com/Gabriel439/Haskell-Dhall-Library/blob/master/exec/Main.hs#L61

**Comment by PierreR** [comment]
> The program name is not inserted by dhall (either the library or the executable). That's inserted by the Haskell runtime system any time an unhandled exception floats up to the top level

Oh I didn't realize that.

> So if you want to get rid of the program name, just catch and handle all exceptions. 

That's what I am doing but it looked like boilerplate a bit ;-)

Thanks for the reply

**Comment by Gabriel439** [comment]
You're welcome!
