### ISSUE TITLE
Try to write a Dhall-to-Nix compiler

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Dhall-Library#4]
Nix lets you import Nix expressions from derivation outputs (although I believe this is still considered experimental), so you could create a Nix derivation that reads in a Dhall configuration file and outputs a Nix expression which could then be referenced by other Nix expressions

This would in turn let you carve out statically typed subsets of Nix projects using Dhall

cc: @domenkozar, who might also be interested in this

**Comment by domenkozar** [comment]
To be honest, exactly this came to my mind a few hours ago after your tweet :)

**Comment by Gabriel439** [comment]
This is now up on Hackage as [the `dhall-nix` package](https://hackage.haskell.org/package/dhall-nix) and you can also find the corresponding Github repository [here](https://github.com/Gabriel439/Haskell-Dhall-Nix-Library)

I'm just waiting for `nixpkgs` to automatically add `dhall-nix` to `haskellPackages` and then I'll open an issue for adding a `dhallToNix` utility to `nixpkgs`.  For reference, the utility looks like this:

```nix
dhallToNix = code :
  let
    file = builtins.toFile "dhall-expr" code;

    drv = pkgs.stdenv.mkDerivation {
      name = "dhall-expr-as-nix";

      buildCommand = ''
        dhall-to-nix <<< "${file}" > $out
      '';

      buildInputs = [ pkgs.haskellPackages.dhall-nix ];
    };
  in
    import "${drv}";
```

You can see example use of this `dhallToNix` utility in the [Nix test suite](https://github.com/Gabriel439/Haskell-Dhall-Nix-Library/blob/master/release.nix#L49) for `dhall-nix`

Once `dhallToNix` utility is upstreamed into `nixpkgs` then I'll mark this issue closed

**Comment by Gabriel439** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/22193

There's also a blog post write-up on this, too: http://www.haskellforall.com/2017/01/typed-nix-programming-using-dhall.html
