### ISSUE TITLE
Feature request: Extract functions from Dhall

### ISSUE THREAD

**Issue by aleator** [Gabriel439/Haskell-Dhall-Library#80]
For my purposes, it could be nice if I could include simple dhall functions in the configuration of my system. Would this be a feasible request for the library as a whole?

**Comment by Gabriel439** [comment]
No, this is not possible in general using the existing `input` approach to interpret and marshal Dhall expressions into Haskell.  In order to do this you would actually have to compile Dhall to Haskell code and compile that into your program at build time

**Comment by aleator** [comment]
Ah, ok. In that case I will just write a custom hack for the function types I need in my own project.

I'm bit curious though why this isn't possible with the current scheme? Of course, you'd need a way to convert some subset of Haskell values to Dhall values for input and you could only decode some specific subset..

**Comment by Gabriel439** [comment]
The hard part is converting polymorphic functions like this type:

```haskell
∀(a : Type) → a → a
```

... or higher-order functions like this type:

```haskell
(Natural → Natural) → Natural
```

**Comment by aleator** [comment]
Ah indeed. I was just thinking about the plain old functions without any of the fancy stuff :).
