### ISSUE TITLE
Getting best mileage with `typeWith`?

### ISSUE THREAD

**Issue by aleator** [Gabriel439/Haskell-Dhall-Library#83]
I'm playing with Dhall (probably in ways it wasn't supposed to be used) and I'm having troubles with the `typeWith` function. What I would want is to have few opaque type name that can be referred to in my config. For most part this works fine, except that `load` does typechecking. This means that I cannot refer to my opaque types in anything that has been imported.

The above is probably by design, but it certainly makes `typeWith` less useful for the end user.  Would a patch that enables passing type context into `load` be acceptable?

**Comment by Gabriel439** [comment]
Yes, I agree that this is worth supporting

**Comment by Gabriel439** [comment]
Closing, as I think this is fixed by #84
