### ISSUE TITLE
Provide a pure version of `input`

### ISSUE THREAD

**Issue by lethom** [Gabriel439/Haskell-Dhall-Library#87]
Hi! I am currently working on a project whichin I would love to use dhall to improve its customization power. However, in order to do so without breaking too many things, I was wondering if it would be possible to use dhall script in pure functions.

That is, I would love to be able to *load and parse* the script once, then *run* it in a pure way several time with different arguments.

Do you think it is possible?

**Comment by Gabriel439** [comment]
The next release of `dhall` will expose the internals of the `Type` constructor: https://github.com/Gabriel439/Haskell-Dhall-Library/commit/0221dd4432c64b0993fdcd19bfb6b83fd353b3a8

... so you will have access to a new `extract` function of type:

```haskell
extract :: Type a -> Expr X X -> Maybe a
```

... and if you apply that to `auto`, it would have type:

```haskell
extract auto :: Interpret a => Expr X X -> Maybe a
```

... which gives you a pure extraction function.  Would that satisfy your use case?

**Comment by lethom** [comment]
That sounds great indeed! What if my dhall script is a function, lets say `\(str: Text) -> ...` which returns a `Text`. My understanding is that currently dhall does not let you just use `input` on the script without an argument, as there is no `Interpret` instance for `Text -> Text`. Will there be such an instance in the next release? Or, do you think such an instance *could be written*? I would be happy to help.

**Comment by Gabriel439** [comment]
Assuming that you have a Dhall function of type `Text → Text` encoded in Haskell as a value of the following type:

```haskell
myDhallFunction :: Expr X X
```

You can turn that into a Haskell function of type `Text -> Text` like this:

```haskell
myHaskellFunction :: Text -> Text
myHaskellFunction input = case extract auto (App myDhallFunction (TextLit input)) of
    Just input -> input
    Nothing    -> error "This shouldn't happen if the function type-checks"
```

I can add an interpret instance that does this for a limited subset of functions but it will take some time because it requires adding a new class, so I would recommend use the above approach for now

**Comment by Gabriel439** [comment]
Sorry, one correction.  It should be:

```haskell
myHaskellFunction :: Text -> Text
myHaskellFunction input = case extract auto (normalize (App myDhallFunction (TextLit input))) of
    Just input -> input
    Nothing    -> error "This shouldn't happen if the function type-checks"
```

**Comment by Gabriel439** [comment]
Here's a first draft of what I have in mind: https://github.com/Gabriel439/Haskell-Dhall-Library/pull/88

It still needs more work though (to add tests, documentation, and generic programming support for user-defined types)

**Comment by lethom** [comment]
Thanks a lot @Gabriel439!

I need some time to process that, as I am not very familiar with the `dhall` package interface. Is the `Dhall.Tutorial` up-to-date with the latest changes you’ve made?

**Comment by Gabriel439** [comment]
The tutorial doesn't explain how to use this yet, but here's an example:

```haskell
>>> :set -XOverloadedStrings
>>> f <- input auto "λ(x : Text) → λ(y : Text) → x ++ y" :: IO (Text -> Text -> Text)
>>> f "ABC" "DEF"
"ABCDEF"
```

**Comment by lethom** [comment]
This is awesome! Thank you very much, that is exactly what I need.

**Comment by Gabriel439** [comment]
Fixed by https://github.com/Gabriel439/Haskell-Dhall-Library/pull/88

**Comment by lethom** [comment]
Thanks for the impressive reactivity. Do you plan to release a new version any time soon?

**Comment by Gabriel439** [comment]
Yes.  I will probably publish a new version within about a week

**Comment by Gabriel439** [comment]
This is now up on Hackage as `dhall-1.5.0`
