### ISSUE TITLE
Revisit precedence of let ... in and type annotation syntax or improve error message

### ISSUE THREAD

**Issue by esmolanka** [Gabriel439/Haskell-Dhall-Library#9]
The following example:

```
let Point = {x : Integer, y : Integer}
in {x = 42, y = -1} : Point
```

Gets parsed as:
```
(let Point = {x : Integer, y : Integer}
in {x = 42, y = -1}) : Point
```

Which leads to a pretty confusing error message, since one might expect that the type annotation will regard only expression `{x = 42, y = -1}` (like in e.g. Haskell).

```
$ ./dhall <<< "let Point = {x : Integer, y : Integer} in {x = 42, y = -1} : Point"

Use "dhall --explain" for detailed errors

Error: Unbound variable

Point

(stdin):1:62
```

Putting record and its type annotation in parentheses fixes this error, but introduces different one (see #10).

```
let Point = {x : Integer, y : Integer}
in ({x = 42, y = -1} : Point)
```

**Comment by Gabriel439** [comment]
This was indirectly fixed by 8df9061fca2544ec9790563a6f888ce5b299c91a (which was designed to fix a similar problem).  Now type annotations bind tighter than `let` expressions:

```bash
$ dhall
let Point = {x : Integer, y : Integer}
in {x = 42, y = -1} : Point
<Ctrl-D>
Use "dhall --explain" for detailed errors

Point : Type

Error: Expression doesn't match annotation

{x = 42, y = -1} : Point

(stdin):2:4
```
