### ISSUE TITLE
Support for recent versions of optparse-generic, vector, etc.?

### ISSUE THREAD

**Issue by peti** [Gabriel439/Haskell-Dhall-Library#94]
Would it be possible to update dhall so that it compiles with recent versions of its dependencies? http://packdeps.haskellers.com/feed?needle=dhall As it is now, we cannot build dhall in neither Nix nor openSUSE, because it doesn't work with a LTS-9.x package set. I suppose, implementing https://github.com/Gabriel439/Haskell-Dhall-Library/issues/16 would go a long way towards avoiding these kind of issues.

**Comment by Gabriel439** [comment]
Yeah!  I will (A) update the dependencies and push a new release to Hackage ASAP and (B) add Dhall to Stackage

**Comment by Gabriel439** [comment]
Fixed in `dhall-1.5.1` on Hackage.  I'll also add to Stackage soon (as tracked by #16)

**Comment by peti** [comment]
Thank you very much for the quick fix!

**Comment by Gabriel439** [comment]
You're welcome!
