### ISSUE TITLE
Document escaping of single quotes

### ISSUE THREAD

**Issue by pmiddend** [Gabriel439/Haskell-Dhall-Library#96]
I'm no sure if I'm just missing this in the `Dhall.Tutorial`, but I was a bit confused by the fact that strings in dhall cannot contain single quotes, as in:

```
{ foo : "bar'baz" }
```

which gives

```
(stdin):1:11: error: expected: "${",
    "''${", "\"", literal character
{foo= "bar'baz"} 
```

Is that even the intended behavior?

**Comment by Gabriel439** [comment]
That's definitely a bug in the parser.  The code example you gave is supposed to be valid Dhall code.  I'll fix this
